theme: minima
title: John Wesley
description: >-
  Engineering Manager and Technology Leader specializing in cloud-native technologies and DevOps practices

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://johnwesley.github.io" # the base hostname & protocol for your site
github_username:  johnwesley
linkedin_username: john-wesley-9222b95a

# Build settings
markdown: kramdown
excerpt_separator: "<!--[ ]*more[ ]*-->"
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock 